#!/bin/bash

docker network create -d bridge taco-testnet
docker network create -d bridge taco-testnet-addr
docker network create -d bridge taco-testnet-ccdb
docker network create -d bridge taco-testnet-orderdb