apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-receiver-service-deployment
spec:
  selector:
    matchLabels:
      app: order-receiver-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: order-receiver-service
    spec:
      containers:
        - name: order-receiver-service
          image: harbour.739.net/taco-cloud/order-receiver:0.0.3
          envFrom:
            - configMapRef:
                name: config-order-receiver-service