apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-management-service-deployment
spec:
  selector:
    matchLabels:
      app: delivery-management-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: delivery-management-service
    spec:
      containers:
        - name: delivery-management-service
          image: harbour.739.net/taco-cloud/delivery-management-service:0.0.3-1
          envFrom:
            - configMapRef:
                name: config-delivery-management-service
          ports:
            - containerPort: 9006