apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service-deployment
spec:
  selector:
    matchLabels:
      app: address-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: address-service
    spec:
      containers:
        - name: address-service
          image: harbour.739.net/taco-cloud/address-service:0.0.3
          envFrom:
            - configMapRef:
                name: config-address-service
          ports:
            - containerPort: 9001