apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-service-deployment
spec:
  selector:
    matchLabels:
      app: cc-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cc-service
    spec:
      containers:
        - name: cc-service
          image: harbour.739.net/taco-cloud/cc-service-service:0.0.3
          envFrom:
            - configMapRef:
                name: config-cc-service
          ports:
            - containerPort: 9002