apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-management-service-deployment
spec:
  selector:
    matchLabels:
      app: payment-management-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: payment-management-service
    spec:
      containers:
        - name: payment-management-service
          image: harbour.739.net/taco-cloud/payment-management-service:0.0.3-2
          envFrom:
            - configMapRef:
                name: config-payment-management-service
          ports:
            - containerPort: 9005