apiVersion: v1
kind: Service
metadata:
  name: cc-service
  labels:
    app: cc-service
spec:
  type: NodePort
  ports:
    - nodePort: 32011
      port: 9002
      protocol: TCP
      targetPort: 9002
  selector:
    app: cc-service