apiVersion: v1
kind: Service
metadata:
  name: taco-order-service
  labels:
    app: taco-order-service
spec:
  type: NodePort
  ports:
    - nodePort: 32012
      port: 9004
      protocol: TCP
      targetPort: 9004
  selector:
    app: taco-order-service