apiVersion: v1
kind: Service
metadata:
  name: order-sender-service
  labels:
    app: order-sender-service
spec:
  type: NodePort
  ports:
    - nodePort: 32017
      port: 9003
      protocol: TCP
      targetPort: 9003
  selector:
    app: order-sender-service