apiVersion: v1
kind: Service
metadata:
  name: address-service
  labels:
    app: address-service
spec:
  type: NodePort
  ports:
    - nodePort: 32010
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: address-service