version: '3.8'
services:
  cc-service:
    container_name: cc-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - DB_URL=mongodb://cc-service-mongodb:27017
      - DATABASE=CCServiceDB
      - PASSWD=50m9FiD3
      - USER=rouslan
    image: harbour.739.net/taco-cloud/cc-service-service:0.0.1
    networks:
      - taco-testnet-ccdb
      - taco-testnet
  address-service:
    container_name: address-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - DB_URL=mongodb://address-service-mongodb:27017
      - DATABASE=addressdb
      - PASSWD=50m9FiD3
      - USER=rouslan
    image: harbour.739.net/taco-cloud/address-service:0.0.2
    networks:
      - taco-testnet-addrdb
      - taco-testnet
  order-service:
    ports:
      - '9004:9004'
    container_name: order-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - DB_HOST=order-service-db
      - DB_PORT=27017
    image: harbour.739.net/taco-cloud/taco-order-service:0.0.1-SNAPSHOT
    networks:
      - taco-testnet-orderdb
  order-sender-service:
    ports:
      - '9003:9003'
    container_name: order-sender-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - QHOST=order-rabbitmq
      - QPORT=5672
    image: harbour.739.net/taco-cloud/order-sender:0.0.1-SNAPSHOT
    networks:
      - taco-testnet-order-queue
  order-receiver-service:
    container_name: order-receiver-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - DB_HOST=order-service-db
      - DB_PORT=27017
      - QHOST=order-rabbitmq
      - QPORT=5672
      - ADDR_HOST=http://address-service:9001/address
      - CC_HOST=http://cc-service:9002/creditcard
    image: harbour.739.net/taco-cloud/order-receiver:0.0.1-SNAPSHOT
    networks:
      - taco-testnet
      - taco-testnet-order-queue
      - taco-testnet-orderdb
networks:
  taco-testnet-order-queue:
    external: true
  taco-testnet-ccdb:
    external: true
  taco-testnet-addrdb:
    external: true
  taco-testnet-orderdb:
    external: true
  taco-testnet:
    external: true