version: '3.8'
services:
  cc-service:
    ports:
      - '9002:9002'
    container_name: cc-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - DB_URL=mongodb://cc-service-mongodb:27019
      - DATABASE=CCServiceDB
      - PASSWD=50m9FiD3
      - USER=rouslan
    image: harbour.739.net/taco-cloud/cc-service-service:0.0.1
    networks:
      - taco-testnet
  address-service:
    ports:
      - '9001:9001'
    container_name: address-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - DB_URL=address-service-mongodb
    image: harbour.739.net/taco-cloud/address-service:0.0.2
    networks:
      - taco-testnet
  order-service:
    ports:
      - '9004:9004'
    container_name: order-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - DB_HOST=order-service-db
    image: harbour.739.net/taco-cloud/taco-order-service:0.0.1-SNAPSHOT
    networks:
      - taco-testnet
  order-sender-service:
    ports:
      - '9003:9003'
    container_name: order-sender-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - QHOST=order-rabbitmq
    image: harbour.739.net/taco-cloud/order-sender:0.0.1-SNAPSHOT
    networks:
      - taco-testnet
  order-receiver-service:
    container_name: order-receiver-service
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - DB_HOST=order-service-db
      - QHOST=order-rabbitmq
      - ADDR_HOST=http://address-service:9001/address
      - CC_HOST=http://cc-service:9002/creditcard
    image: harbour.739.net/taco-cloud/order-receiver:0.0.1-SNAPSHOT
    networks:
      - taco-testnet
networks:
  taco-testnet:
    external: true