version: '3.8'
services:
  mongo:
    ports:
      - '27019:27017'
    container_name: cc-service-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rouslan
      - MONGO_INITDB_ROOT_PASSWORD=50m9FiD3
      - MONGO_INITDB_DATABASE=CCServiceDB
    image: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro