version: '3.8'
services:
  order-service-db:
    container_name: order-service-db
    domainname: order-service-db
    command:
      - mongod --port 27020
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rouslan
      - MONGO_INITDB_ROOT_PASSWORD=50m9FiD3
      - MONGO_INITDB_DATABASE=OrderDB
    image: mongo
    networks:
      - taco-testnet-orderdb
    volumes:
      - ./order-service-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  order-rabbitmq:
    image: rabbitmq:management
    networks:
      - taco-testnet
    container_name: order-rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - type: bind
        source: ./order-rabbitmq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./order-rabbitmq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./order-rabbitmq/rabbitmq-defs.json
        target: /etc/rabbitmq/definitions.json
  cc-service-mongodb:
    ports:
      - '27019:27017'
    container_name: cc-service-mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rouslan
      - MONGO_INITDB_ROOT_PASSWORD=50m9FiD3
      - MONGO_INITDB_DATABASE=CCServiceDB
    image: mongo
    networks:
      - taco-testnet
    volumes:
      - ./cc-service-mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  address-service-mongodb:
    ports:
      - '27018:27017'
    container_name: address-service-mongodb
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rouslan
      - MONGO_INITDB_ROOT_PASSWORD=50m9FiD3
      - MONGO_INITDB_DATABASE=addressdb
    image: mongo
    networks:
      - taco-testnet
    volumes:
      - ./address-service-mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  taco-testnet-orderdb:
    external: true
  taco-testnet:
    external: true
