version: '3.8'
services:
  order-service-mongodb:
    container_name: order-service-mongodb
    restart: unless-stopped
    command: [ "mongod", "--port", "27020" ]
    logging:
      options:
        max-size: 50m
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rouslan
      - MONGO_INITDB_ROOT_PASSWORD=50m9FiD3
      - MONGO_INITDB_DATABASE=OrderDB
    image: mongo
    networks:
      - taco-testnet
    volumes:
      - ./order-service-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  order-rabbitmq:
    image: rabbitmq:management
    networks:
      - taco-testnet
    container_name: order-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - type: bind
        source: ./order-rabbitmq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./order-rabbitmq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.conf
      - type: bind
        source: ./order-rabbitmq/rabbitmq-defs.json
        target: /etc/rabbitmq/definitions.json
  cc-service-mongodb:
    container_name: cc-service-mongodb
    restart: unless-stopped
    command: [ "mongod", "--port", "27019" ]
    logging:
      options:
        max-size: 50m
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rouslan
      - MONGO_INITDB_ROOT_PASSWORD=50m9FiD3
      - MONGO_INITDB_DATABASE=CCServiceDB
    image: mongo
    networks:
      - taco-testnet
    volumes:
      - ./cc-service-mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  address-service-mongodb:
    container_name: address-service-mongodb
    restart: unless-stopped
    command: [ "mongod", "--port", "27018" ]
    logging:
      options:
        max-size: 50m
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rouslan
      - MONGO_INITDB_ROOT_PASSWORD=50m9FiD3
      - MONGO_INITDB_DATABASE=addressdb
    image: mongo
    networks:
      - taco-testnet
    volumes:
      - ./address-service-mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
networks:
  taco-testnet:
    external: true
